apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user_default_role
  namespace: default
subjects:
  - kind: User
    name: jenkins
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: role
  name: user_default_role