apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  volumeName: mypv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
