apiVersion: v1
kind: Pod
metadata:
  labels:
    os: centos
  name: toleration-app
  namespace: default
spec:
  hostname: toleration-app
  containers:
  - image: centos:latest
    imagePullPolicy: Always
    name: toleration-app
    resources:
      limits:
        memory: '128Mi'
        cpu: '250m'
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker2.5el.com.ua
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: app
    operator: Exist
  - effect: NoSchedule
    key: app
    value: backend