apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
  annotations:
    ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  rules:
    - host: viaf.pp.ua
      http:
        paths:
          - backend:
              service:
                name: php-apache
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
  - hosts:
    - viaf.pp.ua
    - www.viaf.pp.ua
    secretName: viaf.pp.ua